account/urls.py
from django.urls import path
from .views import RegisterView, MyProfileView, UserUpdateView
from django.contrib.auth.views import (LoginView, 
                                       LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView)


app_name = "account"
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('my-profile/', MyProfileView.as_view(), name='my_profile'),
    path('profile-update/<int:id>/', UserUpdateView.as_view(), name='profile_update'),
    path('pass-change/', PasswordChangeView.as_view(), name='pass-change'),
    path('pass-change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('pass-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('pass-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('pass-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('pass-reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomePageView, AddNewView, MyNewsView, AllNewsView, NewDetailView, NewUpdateView, NewDeleteView, SearchView, CategoryPageView

app_name = "home"
urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('add-new/', AddNewView.as_view(), name='add_new'),
    path('detail-new/<uuid:uuid>/', NewDetailView.as_view(), name='new_detail'),
    path('new-update/<uuid:uuid>/', NewUpdateView.as_view(), name='new_update'),
    path('new-delete/<uuid:uuid>/', NewDeleteView.as_view(), name='new_delete'),
    path('my-news/', MyNewsView.as_view(), name='my_news'),
    path('all-news/', AllNewsView.as_view(), name='all_news'),
    path('search/', SearchView.as_view(), name='search'),
    path('category/<uuid:uuid>/', CategoryPageView.as_view(), name='category'),
]

home/models.py
from django.db import models
from .manager import BaseModels
from ckeditor.fields import RichTextField
from account.models import User
from hitcount.models import HitCountMixin, HitCount
# Create your models here.

class Category(BaseModels):
    name = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoriyalar'

    def __str__(self) -> str:
        return self.name


class Tags(BaseModels):
    name = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Taglar'

    def __str__(self) -> str:
        return self.name
    

class News(BaseModels, ):
    title = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    body = RichTextField()
    image = models.ImageField(upload_to='news')
    video = models.FileField(upload_to='news_video', null=True, blank=True)
    view_count = models.BigIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="news_category")
    tags = models.ManyToManyField(Tags)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="news_user")
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Yangilik'
        verbose_name_plural = 'Yangiliklar'

    def __str__(self) -> str:
        return self.title

home/forms.py
from django import forms
from .models import News
from ckeditor.fields import RichTextFormField
from ckeditor.widgets import CKEditorWidget


class AddNewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'description', 'image', 'body', 'video', 'category', 'tags', 'is_active']
       

home/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, DetailView, ListView, CreateView, UpdateView, DeleteView
from .models import News, Category
from .forms import AddNewsForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from hitcount.views import HitCountDetailView
# Create your views here.


class HomePageView(View):
    def get(self, request):
        news = News.objects.filter(is_active=True).order_by('-create_at')[:10]
        context = {
            'news' : news
        }
        return render(request, 'home.html', context)


class AddNewView(LoginRequiredMixin, CreateView):
    model = News
    form_class = AddNewsForm
    template_name = "add_new.html"
    success_url = reverse_lazy("home:home_page")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form )


class MyNewsView(LoginRequiredMixin, ListView, View):
    template_name = 'my_news.html'
    model = News
    count_hit = True
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['my_news'] = News.objects.filter(user=self.request.user).order_by('-create_at')
        return context


class AllNewsView(LoginRequiredMixin, View):
    def get(self, request):
        if self.request.user.is_superuser:
            all_news = News.objects.filter(user=self.request.user).order_by('-create_at')
            context ={
                'all_news' : all_news
            }
        return render(request, 'all_news.html', context)
    

class NewDetailView(HitCountDetailView):
    count_hit = True
    def get(self, request, uuid):
        news = News.objects.filter(is_active=True, uuid=uuid)
        category = News.objects.filter(is_active=True, category=news[0].category).order_by('-create_at')[:3]
        for i in category:
            if i.uuid==news[0].uuid:
                category = News.objects.filter(is_active=True, category=news[0].category).order_by('-create_at')[:4]
                break
        context = {
            'new_detail' : news,
            'recomendation' : category,
        }
        return render(request, 'new_detail_page.html', context)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hit_count'] = self.get_hit_count()
        return context


class NewUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView, HitCountDetailView):
    model = News
    template_name = "new_update.html"
    form_class = AddNewsForm
    count_hit = True
    
    def get_object(self, queryset=None):
        return News.objects.get(uuid=self.kwargs['uuid'])
    
    def get_success_url(self) -> str:
        uuid = self.kwargs['uuid']
        return reverse("home:new_detail", kwargs={'uuid':uuid})
    
    def test_func(self) -> bool | None:
        obj = self.get_object()
        return obj.user == self.request.user or self.request.user.is_superuser


class NewDeleteView(LoginRequiredMixin, UserPassesTestMixin, HitCountDetailView):
    count_hit = True
    template_name = 'new_delete.html'

    def get(self, request, uuid):
        new_delete = News.objects.filter(uuid=uuid)
        return render(request, self.template_name, {'new_delete':new_delete})

    def post(self, request, uuid):
        object = get_object_or_404(News, uuid=uuid)
        object.is_active = False
        object.save()
        return redirect('home:home_page')

    def test_func(self) -> bool | None:
        obj = get_object_or_404(News, uuid=self.kwargs['uuid'])
        return obj.user == self.request.user or self.request.user.is_superuser


class SearchView(ListView):
    template_name = 'search.html'
    model = News

    def get_queryset(self) -> QuerySet[Any]:
        query = self.request.GET.get("search")
        object_list = News.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query) | Q(body__icontains=query)
        )
        return object_list

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get("search")
        return context
    

class CategoryPageView(HitCountDetailView):
    count_hit = True
    def get(self, request, uuid):
        category = Category.objects.get(uuid=uuid)
        news_category = category.news_category.all().order_by('-create_at')
        context = {
            'news' : news_category
        }
        return render(request, 'home.html', context)

templates/add_new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <h1>Add New Page</h1>
    </div>
    <div class="m-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Saqlash</button>
            <a href="{% url 'home:home_page' %}">Back home</a>
        </form>
    </div>
{{ form.media }}
{% endblock %}

templates/all_news.html
{% extends "base.html" %}
{% block content %}

<div>
    <h1>All News Page</h1>
</div>
<div class="container">
    {%  for all_news in all_news %}
        <h1><a href="{% url 'home:new_detail' uuid=all_news.uuid %}">{{ all_news.title }}</a></h1> 
        <h3>{{ all_news.description }}</h3>
        <img src="{{ all_news.image.url }}" width="300">
        <p>View : {{ all_news.view_count }}     Create user : {{ all_news.user }}     Create at : {{ all_news.create_at }}     Is active : {{ all_news.is_active }}</p>
        <br>
    {% endfor %}
    <a href="{% url 'home:home_page' %}">Back home</a>
</div>
{% endblock content %}

templates/base.html
{% load static %}
{% load hitcount_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <a href="{% url 'home:home_page' %}">All</a>
        {% for category in category %}
            <a href="{% url 'home:category' uuid=category.uuid %}">{{ category.name }}</a>
        {% endfor %}
    </div>

    <br>
    <div>
        {% if request.user.is_authenticated %}
            <form method="post" action="{% url 'account:logout' %}">
                {% csrf_token %}
                <input type="submit" value="Logout">
            </form>
            <a href="{% url 'account:my_profile' %}">My Profile : <b>{{ request.user }}</b></a>
        {% else %}
            <a href="{% url 'account:login' %}">SignIn</a>
            <a href="{% url 'account:register' %}">SignUp</a>
        {% endif %}
    </div>
    <div>
        <form action="{% url 'home:search' %}" method="get">
            <input type="search" placeholder="Search" aria-label="Search" name="search">
            <button type="submit">Search</button>
        </form>
    </div>
    
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load hitcount_tags %}
{% block content %}

<div>
    <h1>Home Page</h1>
</div>

<div class="container">
    {% if news %}
        {%  for news in news %}
            <h1><a href="{% url 'home:new_detail' uuid=news.uuid %}">{{ news.title }}</a></h1> 
            <h3>{{ news.description }}</h3>  
            <img src="{{ news.image.url }}" width="300">
            <p>{{ news.create_at }}  |  {{ hit_count }}</p>
        {% endfor %}
    {% else %}
        <h3>Ushbu kategoriya bo'yicha hech qanday malumot topilmadi.</h3>   
    {% endif %}
    
</div>
{% endblock content %}

templates/my_news.html
{% extends "base.html" %}
{% block content %}

<div>
    <h1>My News Page</h1>
</div>
<div class="container">
    {%  for my_news in my_news %}
        <h1><a href="{% url 'home:new_detail' uuid=my_news.uuid %}">{{ my_news.title }}</a></h1> 
        <h3>{{ my_news.description }}</h3>
        <img src="{{ my_news.image.url }}" width="300">
        <p>View : {{ my_news.view_count }}     Create user : {{ my_news.user }}     Create at : {{ my_news.create_at }}     Is active : {{ my_news.is_active }}</p>
        <br>
    {% endfor %}
    <a href="{% url 'home:home_page' %}">Back home</a>
</div>
{% endblock content %}

templates/my_profile.html
{% extends "base.html" %}
{% block content %}

<div>
    <h1>Profile page</h1>
</div>
<div class="container">
    {% for profile in profile %}
        {% if profile.avatar %}
            <img src="{{ profile.avatar.url }}">
        {% endif %}
        <h3>Profil username: {{ profile.username }}</h3>
        <p>Fisrt name : {{ profile.first_name }}</p>
        <p>Last name : {{ profile.last_name }}</p>
        <p>Email : {{ profile.email }}</p>
        <p>Phone : {{ profile.phone }}</p>
        <p>Adress : {{ profile.address }}</p>
        <a href="{% url 'home:add_new' %}">Add new</a> /
        <a href="{% url 'home:my_news' %}">My news</a>
        {% if request.user.is_superuser %}
            /<a href="{% url 'home:all_news' %}">All news</a>
        {% endif %}
        <br><br>
        <a href="{% url 'account:pass-change' %}">Parolni o'zgartirish</a>
        <br><br>
        <a href="{% url 'account:profile_update' profile.id %}">Malumotlarni yangilash</a>
        <br><br>
        <form action="{% url 'account:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    {% endfor %}
</div>

{% endblock content %}

templates/new_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="m-4">
    <h3>New Delete Page</h3>
    {% for new_delete in new_delete %}
    <p>Haqiqatdan ham bu yangilikni o'chirmoqchimisiz?</p>
    <h3>{{ new_delete.title }}</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">O'chirish</button>
        <a href="{% url 'home:new_detail' new_delete.uuid %}">Orqaga</a>
    </form>
    {% endfor %}
</div>
    
{% endblock content %}

templates/new_detail_page.html
{% extends "base.html" %}
{% load hitcount_tags %}
{% block content %}

<div>
    <h1>News Detail Page</h1>
</div>
<div class="container">
    {%  for new_detail1 in new_detail %}
        <h1>{{ new_detail1.title }}</h1>
        <h3>{{ new_detail1.description }}</h3>
        <img src="{{ new_detail1.image.url }}" width="300">
        <p>{{ new_detail1.body|safe }}</p>
        <p><i class="fa fa-eye aria" aria-hidden="true"></i>hit counts: {% get_hit_count for new_detail %}  |  {{ new_detail1.create_at }}</p>
        <p>News category : {{ new_detail1.category }}</p>
        <p>News tags : </p>
        <ul>
            {% for tags in new_detail1.tags.all %}
                <li>{{ tags.name }}</li>
            {% endfor %}
        </ul>
        <br>
        {% if request.user == new_detail1.user or request.user.is_superuser%}
            <p>Is active : {{ new_detail1.is_active }}</p>
            {% if new_detail1.is_active == True %}
                <a href="{% url 'home:new_delete' uuid=new_detail1.uuid %}">O'chirish</a>/
            {% elif request.user.is_superuser and new_detail1.is_active == False %}
                <a href="{% url 'home:new_delete' uuid=new_detail1.uuid %}">O'chirish</a>/
            {% endif %}
            <a href="{% url 'home:new_update' uuid=new_detail1.uuid %}">Tahrirlash</a>
            <br>
        {% endif %}
        <br><br>
        {%  for news in recomendation %}
            {% if not news.uuid == new_detail1.uuid %}
                <h1><a href="{% url 'home:new_detail' uuid=news.uuid %}">{{ news.title }}</a></h1> 
                <h3>{{ news.description }}</h3>  
                <img src="{{ news.image.url }}" width="300">
                <p>View : {{ news.view_count }}                       Create at : {{ news.create_at }}</p>
            {% endif %}
        {% endfor %}
    {% endfor %}
    <a href="{% url 'home:home_page' %}">Back home</a>
</div>
{% endblock content %}

templates/new_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <h1>Update New Page</h1>
    </div>
    <div class="m-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Saqlash</button>
            <a href="{% url 'home:new_detail' object.uuid %}">Orqaga</a>
        </form>
    </div>
{{ form.media }}
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block content %}

<div>
    <h1>Search Page</h1>
</div>
<div>
    <p><b>{{ query }}</b> bo'yicha qidiruv natijalari soni : <b>{{ object_list|length }}</b></p>
</div>
<div class="container">
    {%  for query in object_list %}
        <h1><a href="{% url 'home:new_detail' query.uuid %}">{{ query.title }}</a></h1> 
        <h3>{{ query.description }}</h3>  
        <img src="{{ query.image.url }}" width="300">
        <p>View : {{ query.view_count }}                       Create at : {{ query.create_at }}</p>
    {% endfor %}
    <a href="{% url 'home:home_page' %}">Back to home</a>
</div>

{% endblock content %} 

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rich Text Editor</title>
  <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      tinymce.init({
        selector: '#editor',
        height: 300,
        plugins: 'advlist autolink lists link image charmap print preview anchor',
        toolbar: 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | link image',
      });
    });
  </script>
</head>
<body>
  <img src="http://localhost:8000/media/news/Screenshot_2023-12-17_233641.png" alt="">
  <textarea id="editor">Start typing here...</textarea>

</body>
</html>